### ISSUE TITLE
Explore to support the record with optional field.

### ISSUE THREAD

**Issue by mununki** [green-labs/ppx_spice#18]
```rescript
@spice
type t = {
  name?: string,
  age?: int
}
```

**Comment by hellos3b** [comment]
Ooh just ran into this. Are there any workarounds available?

**Comment by mununki** [comment]
> Ooh just ran into this. Are there any workarounds available?

Not yet. I couldn't grab a time to make it support the optional field record yet.
I'll try to grab a time to make it work soon.

**Comment by mununki** [comment]
@hellos3b I fixed and merged to master. let you know once the publishing to npm is done.

**Comment by mununki** [comment]
@hellos3b You can try v0.1.7-rc1 https://www.npmjs.com/package/@greenlabs/ppx-spice/v/0.1.7-rc1

**Comment by hellos3b** [comment]
@mununki hey, thanks for looking at this so quickly! 

I just installed rc1 and gave it a shot, and I'm getting an error I'm not familiar with -- is this an environment thing on my end? Anything sound... familiar?

I'mg etting this when running `rescript build`

```
rescript: [2/6] src/internal/Build.ast
FAILED: src/internal/Build.ast
Fatal error: exception (Invalid_argument "option is None")

  We've found a bug for you!
  /Users/seb/workspace/src/internal/Build.res

  Error while running external preprocessor
Command line: /Users/seb/workspace/node_modules/@greenlabs/ppx-spice/ppx '/var/folders/5g/wzfmdzfn09l1pnpb5gd4l72m0000gn/T/ppx0c0afeBuild.res' '/var/folders/5g/wzfmdzfn09l1pnpb5gd4l72m0000gn/T/ppx7dcc19Build.res'


FAILED: cannot make progress due to previous errors.
>>>> Finish compiling(exit: 1)
```

**Comment by mununki** [comment]
@hellos3b Not familiar to me though. Can you show me the code that is using `@spice` and exception Invalid Argument?

**Comment by hellos3b** [comment]
I created a blank repo, installed rescript and rc1 and tried to build, still getting it

bsconfig.json

```json
{
  "name": "spice_test",
  "sources": [
    {"dir": "src", "subdirs": true}
  ],
  "package-specs": [
    {
      "module": "es6",
      "in-source": true
    }
  ],
  "suffix": ".bs.js",
  "bs-dependencies": [
    "@greenlabs/ppx-spice"
  ],
  "bsc-flags": ["-open Belt"],
  "ppx-flags": ["@greenlabs/ppx-spice/ppx"],
  "reanalyze": {
    "analysis": ["exception"]
  },
  "gentypeconfig": {
    "language": "typescript",
    "shims": {},
    "generatedFileExtension": ".gen.ts",
    "module": "es6",
    "debug": {
      "all": false,
      "basic": false
    }
  }
}
```

Main.res
```res
@spice.decode
type user = {
  email: string,
  name: string
}

let main = () => {
  let u = user_decode(Obj.magic({"email": "abc", "name": "abcd"}))
  Js.Console.log(u)
}
```

Error
```
 ~/workspace/localhost/spice | on main ?5  npx rescript build -verbose                                                                                                                                                 ok | at 09:31:08 
BSB check build spec : /Users/seb/workspace/localhost/spice/node_modules/.pnpm/registry/node_modules/rescript/darwinarm64/rescript.exe 
Package @greenlabs/ppx-spice -> /Users/seb/workspace/localhost/spice/node_modules/@greenlabs/ppx-spice
ninja.exe -C lib/bs 
rescript: [1/3] src/Main.ast
FAILED: src/Main.ast
Fatal error: exception (Invalid_argument "option is None")

  We've found a bug for you!
  /Users/seb/workspace/localhost/spice/src/Main.res

  Error while running external preprocessor
Command line: /Users/seb/workspace/localhost/spice/node_modules/@greenlabs/ppx-spice/ppx '/var/folders/5g/wzfmdzfn09l1pnpb5gd4l72m0000gn/T/ppx5b709eMain.res' '/var/folders/5g/wzfmdzfn09l1pnpb5gd4l72m0000gn/T/ppxd0da73Main.res'


FAILED: cannot make progress due to previous errors.
```

**Comment by mununki** [comment]
@hellos3b Can you try this?
```rescript
@spice
type user = {
  email: string,
  name: string
}
```

**Comment by hellos3b** [comment]
@mununki Yup can confirm that works, even with the optional field!

**Comment by mununki** [comment]
> @mununki Yup can confirm that works, even with the optional field!

Thanks for the feedback!

**Comment by osener** [comment]
@mununki I hit the same error as @hellos3b. Is there any reason spice can't be used to _only_ generate decoders or encoders and not both?

At Tella we use Spice and Decco. I would like to switch to using Spice exclusively but this is preventing us from using it as a drop-in replacement.

**Comment by mununki** [comment]
@osener Can you elaborate on a self-contained example to look at?

**Comment by osener** [comment]
@mununki I first thought `@spice.encode` was not supported at all based on the discussion above, but I think this issue is limited to custom encoders/decoders. I created an issue: https://github.com/green-labs/ppx_spice/issues/40
